### PR TITLE
Issue15

### PR DESCRIPTION
**Pull request by Myde001**
Hi Rob, 

I have been able to update my branch, included the test cases, test files and updated the makefile.  Kindly review for merge.

Regards,
Olumide

### CODE REVIEW

**Comment by robbarwell123** [comment]
Good Morning Olu,

If you're happy with your changes you can submit a pull request and I can
add comments to it if you want along with everyone else.  Just make sure
when you do the following commands everything works as expected.

'make clean'
'make'
'make run'
'make run_test'

If not you might have to go back and review a couple things.  Also make run
and make run_test might work slightly differently on Mac as I don't know
what it compiles the executable to.

Cheers
Rob

**Review by lukemanhakkim — APPROVED** [review]
Seems good to me.

**Comment by robbarwell123** [comment]
Hi Olu,

I had trouble compiling your files.  I would recommend you look at the following.  Let me know when you're done making the changes and I will try again.

1.	Make File
	a.	Double check the spelling for helper_functions.o when it is used in the file
	b.	Add helper_functions.o and parse_airports.o to test
	c.	Add parse_airports_test.o to the test command
	d.	Double check to ensure everything compiles without issues
2.	Make sure to use header guards on all header files
3.	Consider using #ifdef DEBUG_ENABLED around any printed text you want for debug purposes that isn't part of the specified program output.
4.	Check the comment format at the top of files to ensure it is consistent and matches the Doxygen format
5.	I would recommend changing the file name for helper_functions.h and .c to something that matches parse_airport.  For example I included parse_config in strat_airlift_functions.h and then used parse_config.h to include my helper functions.
6.	Don't forget to use all lower snake case for file names
7.	parse_airports is defined in both parse_airport.c and parse_airport_test.c which causes compilation issues.  You should review your test cases to ensure they all run successfully.

Cheers
Rob

**Comment by Myde001** [comment]
Hi Rob,

Please I am pretty new to running codes using make file, can we do it
together by tomorrow?

Regards,
Olumide

**Comment by robbarwell123** [comment]
Hi Olu,

Please see the code here:
https://drive.google.com/file/d/1iN3NLdrvR2h0YFTlPqfVrlrmgz3ANzCt/view?usp=sharing
It has an example of how to modify the makefile and build test cases out
and integrate the functions into the main function.  Let me know when you
have reviewed the files and we can talk further.  The specific files I
would focus on are:

makefile
src/
    main.c
    gen_locations.c
include/
    main.h
    strat_airlift_functions.h
    gen_locations.h
    data_types.h
test/src/
    test_main.c
    gen_locations_test.c
test/include/
    gen_locations_test.h
    strat_airlift_functions_tests.h

Cheers
Rob

**Review by lukemanhakkim — APPROVED** [review]

**Comment by Myde001** [comment]
Hi All, 

I have updated my functions, 

I ran the make, everything compiled. 

make run, everything checked.
make run_test, all functions checked except calc_shortest_path_test, which Rob will revise. 

Regards, 
Olumide

**Review by robbarwell123 — APPROVED** [review]
Looks good to me.  We can take care of the test error when we do a review of the whole program once everyone checks in their pieces.

Cheers
Rob

**Comment by edwin-omoigui** [comment]
Looks good to merge

**Review by edwin-omoigui — APPROVED** [review]
Looks good to merge

**Pull request merged**
