### PR TITLE
Issue13

### PR DESCRIPTION
**Pull request by Myde001**
Dear All,

Kindly review my integration test and approve the pull request. 

Regards,
Olumide

### CODE REVIEW

**Comment by robbarwell123** [comment]
Good Afternoon Olu,

1. Lukeman's function will output 2 different files Locations.xml and LocInfo.txt.  In the test/data folder you should have two files "Locations_correct.xml" and "LocInfo_correct.txt" to use for comparison.
2. test/include/strat_airlift_functions_tests.h - Consider adding more information to the Doxygen comment for integrated_test()
3. You need to compare both Locations_Correct.xml and LocInfo_correct.txt.  You should have two comparison functions.  These functions should be commented out until Lukeman's function is completed.

Cheers
Rob

**Review by robbarwell123 — APPROVED** [review]
Looks good with the new changes.  Thank you for addressing them.

Cheers
Rob

**Review by edwin-omoigui — APPROVED** [review]
Looks good to merge

**Review by lukemanhakkim — APPROVED** [review]
Looks good we can add it.

**Pull request merged**
