### PR TITLE
Issue 18 19

### LINKED ISSUE #18: Exporting the graph data

### LINKED ISSUE #19: Exporting output files : Location Shortest path text file and  Location XML file

### PR DESCRIPTION
**Pull request by lukemanhakkim**

### CODE REVIEW

**Comment by robbarwell123** [comment]
Good Morning Lukeman,

I have reviewed your pull request and noted the following:
1. You have an extra .vscode folder in the commit.  This can be removed by add it to .gitignore.
2. Your pull request is from issue_18_19 to master, your pull request should be from issue_18_19 to development.
3. You accidentally edited the README.md file and added "make " at the top.  This should be removed.
4. General - Anytime you update an existing file you should update the comment at the top with the last update date.  Please also review the coding conventions and review all your files for things like variable names, indentation spacing, brackets, comments etc ...
4. include/export.h - Based on your comments I noticed some functions only pass a return value of 0, if this is correct it should be a void function, if not please update the comment.
5. include/strat_airlift_functions.h - You have export_text and export_xml defined in this file and export.h, this file should only include the function from the requirements document "int export(struct STATE *my_state, struct PATH *my_paths, char *output_directory)" which should be added and called from main.c.
6. src/main.c - I received a "Unable to create file." error when running the program.  This is most likely due to the hard coded file name in main.c.  Main.c needs to be updated to call "int export(my_state, my_paths, output_dir+curr_scenario)" so individual files per scenario are generated in the output directory.
7. src/export.c - You need to include all relevant header files. The output themselves is correct, however they could use some formatting with the correct indentation.  I would also open the files in overwrite and not append as you need one file per scenario.  You also need to add code to check if the output file and directory exist and if not you need to create it.  I would recommend adding the directory checking code once in the export() function.
8. test/src/export_test.c - Please complete this function.  Please check your header includes, whether variables are used, and the test itself (i.e. what are you comparing).

I will do a more detailed review once these comments are addressed.

Cheers
Rob

**Comment by lukemanhakkim** [comment]
Hi Rob, 

I have addressed the following changes:

1. Removed unwanted .vscode folder from the repo.
2. Changed the PR from issue_18_19 to development branch.
3. Removed unwanted "make" from README.md.
4. Updated for the files i have changed.
5. Changed the int functions to void functions.
6. Added the "int export(struct STATE *my_state, struct PATH *my_paths, char *output_directory)" to the main.c file.
7. This functionality is done. In this commit i have used a static path to test the functionality, both in main.c as well as test_main.c
8. Changed the file operation from append to overwrite mode, added support to check the existence of directory if not it will create the same input directory.
9. added testcase to check the existence of generated test and xml file.

It seems there is a merge conflict with this branch, need your suggestion to resolve the issue.

**Comment by robbarwell123** [comment]
Hi Lukeman,

Are you able to provide more details about what issues you are facing with the merge?  When merging you need to look at the two files and determine what changes need to overwrite others.  There shouldn't be many changes you need to do in the development branch files so you can probably take them as is, but you will need to compare one by one.

I also looked at your latest code base and have the following comments:
1. I couldn't build your program using make.  When I resolved the build issues I couldn't see any output.  Please make sure the program runs prior to the next code review request.  I would recommend you do the merge from development into your branch and then compile, run, and test using the latest program.
2. Please review and adhere to coding and documentation (doxygen) conventions.  You can double check your doxygen generation by using "make doxygen".
3. You still need to complete your export unit test by using a known start state and checking that your function produces the expected output.  You can review Olu's integration test for an example of this where he compares the output file to an existing output file.  You both can probably share the same known output state files.

Cheers
Rob

**Comment by lukemanhakkim** [comment]
Hi team,

1. To resolve the mkdir issue i have defined the function mkdir and imported two libraries #include <sys/stat.h>, #include <sys/types.h> 
   to support the functionality. It solved the  issue we were facing when the code is executed in linux environment..
2. I have added Unitest cases for export function. Below are the test scenarios:
     (i).  Checking the existence of generated Locations.xml
     (ii). Checking the existence of generated LocInfo.txt
     (iii). Comparing the expected xml data with the generated xml data.
     (iv). Comparing the expected text data with the generated text data.

Kindly review my PR with the latest code.

**Review by robbarwell123 — APPROVED** [review]
Good Morning Lukeman,

I have spent the past couple hours reviewing your pull request and since the deadline is tomorrow I have corrected these issues.  Below please find a summary of what has been done.

1. include/common_functions.h
    - Removed mkdir from common_functions.h as it produced a "Segmentation fault (core dumped)" error when passed a nested directory to create (i.e. ./bin/StratAirliftInit -o ./output/test1/).  This is most likely due to it being declared, but not defined and over riding the system function in sys/stat.h.
    - Added sys/stat.h and sys/types.h to export.c and export_test.c to produce the expected behavior
    - Corrected doxygen comments and errors
2. include/export.h
    - Removed duplicate header imports
    - Corrected doxygen comments and errors
3. src/export.c
    - Resolved many coding convention issues.  There were too many to list here.
    - When generating the xml file the file handle wasn't close and therefore caused issues in the unit test
4. test/src/export_test.c
    - Removed unused variables
    - Created a common test functions file to refactor the code due to sharing the functions I created with the calc shortest path test
    - Added screen output for the status of each test case run, including the expected output if it is not correct.
    - Resolved many coding convention issues including indentation, brackets, function names, etc ...
    - Resolved multiple logic errors
        - You checked for a file to be opened and if it wasn't you still read from it
        - You always returned true regardless and prevented the free memory statements from executing
        - Corrected LocInfo_correct.txt with the correct light endings to match the generated file
        - Corrected logic in compare_files as a blank output file would pass as correct

I have now successfully reviewed this pull request and once Edwin and Olu have approved it you can merge it and I will do a final review before the pull request from development to master.

Cheers
Rob

**Review by Myde001 — APPROVED** [review]
Approved on my end

**Review by edwin-omoigui — APPROVED** [review]
Reviewed ok

**Pull request merged**
