### PR TITLE
Closes #20

### LINKED ISSUE #1: Create header file(s) for structures
Include the following structures:
1.  AIRPORT;
2.  STATE;
3.  PATH

### LINKED ISSUE #20: Create release 1 static initial generator state
This feature is to create a skeleton of reading the config file which will contain the static defaults of the initial generator state.

### PR DESCRIPTION
**Pull request by robbarwell123**
Good Afternoon Everyone,

Please review my pull request to merge issue 20 into the development branch.  This issue provides the bases for the generator and includes the release 1 parse_config function.  This function sets up the default state of the generator to include the defaults from the requirements document.  Below are other changes required to support development of parse_config.

1.  Set up folder structure;
2.  Set up default makefile;
3.  Set up default doxygen config file under the doc directory;
4.  Set up default common functions and common data structures; and
5.  Initial main.c file.

Please review to ensure I followed all the direction from the Prof and the requirements document.  If you have any questions let me know.

Thanks
Rob

### CODE REVIEW

**Comment by Myde001** [comment]
This is good for me. I think it aligns with our proposal

**Review by Myde001 — COMMENTED** [review]
This works for me.

**Comment by lukemanhakkim** [comment]
Its good. We can merge it.

**Comment by edwin-omoigui** [comment]
Reviewed! Good to go!

**Review by edwin-omoigui — APPROVED** [review]
This is good to Go!

**Pull request merged**
