### PR TITLE
Closes #5 and #6 Addition of Shortest Path Calculation

### LINKED ISSUE #5: Implement find the shortest path between locations
Implement calc_shortest function

### LINKED ISSUE #6: Test finding the shortest path between locations
Create and conduct unit testing of calc_shortest

### PR DESCRIPTION
**Pull request by robbarwell123**
Added the following:
- calc_shortest_path including implementing Dijsktra's algorithm
- unit test for calc_shortest_path
- updated all functions to return 0 as success and any other number as failure
- removed unit testing functions from main and brought them to test_main
- setup test_main.c
- extended the makefile to include building a single test executable

Please review to make sure everything follows what the Prof is requesting.

### CODE REVIEW

**Review by edwin-omoigui — APPROVED** [review]
Excellent! Good to merge!

**Comment by lukemanhakkim** [comment]
Its good, we can merge it.

**Review by lukemanhakkim — APPROVED** [review]
Its good, we can merge it.

**Review by Myde001 — APPROVED** [review]
Hey Rob, I think we are good to go.

**Pull request merged**
